version: "3.8"

services:
  db:
    image: ankane/pgvector:latest # Postgres with vector similarity search
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ada
      POSTGRES_USER: human
      POSTGRES_PASSWORD: pass
    ports:
      - "2345:5432" # To avoid conflicts with other Postgres instances

  service:
    build: ./service
    ports: # Public port is 4000, but the container is listening on 4000
      - "4000:4000"
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://human:pass@db:5432/ada
      AUTOCHAT_PROVIDER: anthropic
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
  view:
    build: ./view
    ports:
      - "8080:80"
    depends_on:
      - service

volumes:
  postgres_data:
