[tool.poetry]
name = "service"
version = "0.1.0"
description = ""
authors = ["benderv <benderville@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
openai = "^0.27.2"
requests = "^2.28.2"
SQLAlchemy = "^2.0.6"
Flask = "^2.2.3"
Flask-SocketIO = "^5.3.3"
diskcache = "^5.4.0"
snowflake-connector-python = "^3.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
