"""Add project & fix createdAt & updatedAt

Revision ID: 04c991f0d2ae
Revises: 964d8451f1ba
Create Date: 2024-08-22 08:02:39.065747

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "04c991f0d2ae"
down_revision: Union[str, None] = "964d8451f1ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("creatorId", sa.String(), nullable=False),
        sa.Column("organisationId", sa.String(), nullable=True),
        sa.Column("databaseId", sa.Integer(), nullable=False),
        sa.Column(
            "createdAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updatedAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["creatorId"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["databaseId"],
            ["database.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organisationId"],
            ["organisation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project_tables",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("projectId", sa.Integer(), nullable=False),
        sa.Column("databaseName", sa.String(), nullable=True),
        sa.Column("schemaName", sa.String(), nullable=True),
        sa.Column("tableName", sa.String(), nullable=True),
        sa.Column(
            "createdAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updatedAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["projectId"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_foreign_key(None, "conversation", "project", ["projectId"], ["id"])

    # Add default values to createdAt & updatedAt columns of tables conversation, conversation_message, query
    op.alter_column(
        "conversation", "createdAt", server_default=sa.text("now()"), nullable=False
    )
    op.alter_column(
        "conversation", "updatedAt", server_default=sa.text("now()"), nullable=False
    )
    op.alter_column(
        "conversation_message",
        "createdAt",
        server_default=sa.text("now()"),
        nullable=False,
    )
    op.alter_column(
        "conversation_message",
        "updatedAt",
        server_default=sa.text("now()"),
        nullable=False,
    )
    op.alter_column(
        "query", "createdAt", server_default=sa.text("now()"), nullable=False
    )
    op.alter_column(
        "query", "updatedAt", server_default=sa.text("now()"), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "conversation_projectId_fkey", "conversation", type_="foreignkey"
    )
    op.drop_table("project_tables")
    op.drop_table("project")

    # Drop expressions now() from createdAt & updatedAt columns of tables conversation, conversation_message, query
    op.alter_column("conversation", "createdAt", server_default=None, nullable=True)
    op.alter_column("conversation", "updatedAt", server_default=None, nullable=True)
    op.alter_column(
        "conversation_message", "createdAt", server_default=None, nullable=True
    )
    op.alter_column(
        "conversation_message", "updatedAt", server_default=None, nullable=True
    )
    op.alter_column("query", "createdAt", server_default=None, nullable=True)
    op.alter_column("query", "updatedAt", server_default=None, nullable=True)
    # ### end Alembic commands ###
