"""add reqId

Revision ID: 2af9b2c6c9ea
Revises: 94e7e7175204
Create Date: 2023-08-31 21:05:13.071253

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2af9b2c6c9ea"
down_revision: Union[str, None] = "94e7e7175204"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversation_message", sa.Column("reqId", sa.String(), nullable=True)
    )
    op.drop_column("conversation_message", "done")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversation_message",
        sa.Column("done", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("conversation_message", "req_id")
    # ### end Alembic commands ###
