"""Add image

Revision ID: 5f9469b957c8
Revises: 4a0f8721eb48
Create Date: 2024-09-15 18:53:31.029820

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5f9469b957c8"
down_revision: Union[str, None] = "4a0f8721eb48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversation_message", sa.Column("image", sa.LargeBinary(), nullable=True)
    )
    op.alter_column(
        "conversation_message",
        "functionCallId",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "conversation_message",
        "functionCallId",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_column("conversation_message", "image")
    # ### end Alembic commands ###
