"""Add project

Revision ID: 84dcd574f1c2
Revises: 0e933f6adc06
Create Date: 2024-08-08 08:42:30.459598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84dcd574f1c2'
down_revision: Union[str, None] = '0e933f6adc06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('creatorId', sa.String(), nullable=False),
    sa.Column('organisationId', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['creatorId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['organisationId'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projectId', sa.Integer(), nullable=False),
    sa.Column('databaseName', sa.String(), nullable=True),
    sa.Column('schemaName', sa.String(), nullable=True),
    sa.Column('tableName', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['projectId'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_tables')
    op.drop_table('project')
    # ### end Alembic commands ###
