"""Add createdAt & updatedAt

Revision ID: 964d8451f1ba
Revises: 0e933f6adc06
Create Date: 2024-08-21 15:26:35.049216

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "964d8451f1ba"
down_revision: Union[str, None] = "0e933f6adc06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "database",
        sa.Column(
            "createdAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "database",
        sa.Column(
            "updatedAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "organisation",
        sa.Column(
            "createdAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "organisation",
        sa.Column(
            "updatedAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "createdAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "updatedAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "user_organisation",
        sa.Column(
            "createdAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.add_column(
        "user_organisation",
        sa.Column(
            "updatedAt", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_organisation", "updatedAt")
    op.drop_column("user_organisation", "createdAt")
    op.drop_column("user", "updatedAt")
    op.drop_column("user", "createdAt")
    op.drop_column("organisation", "updatedAt")
    op.drop_column("organisation", "createdAt")
    op.drop_column("database", "updatedAt")
    op.drop_column("database", "createdAt")
    # ### end Alembic commands ###
