"""make query colum optional

Revision ID: b7c451b82bc1
Revises: e230a2ea7169
Create Date: 2023-11-16 18:08:37.255433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b7c451b82bc1"
down_revision: Union[str, None] = "e230a2ea7169"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("query", "query", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("query", "query", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
