"""clean column name

Revision ID: e230a2ea7169
Revises: 5642e37ccbfa
Create Date: 2023-11-15 13:50:42.964341

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e230a2ea7169"
down_revision: Union[str, None] = "5642e37ccbfa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename query.validatedSQL to query.sql
    op.alter_column("query", "validatedSQL", new_column_name="sql")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename query.sql to query.validatedSQL
    op.alter_column("query", "sql", new_column_name="validatedSQL")

    # ### end Alembic commands ###
